apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/hajle-silesia/container-orchestration-cd.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{index .path.segments 1}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/hajle-silesia/container-orchestration-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
